# This privacy policy is just an example

# The regulation of GDPR does not apply to purely personal activities

PrivacyPolicyEnabled = false

PrivacySettingsVersion = 1

PrivacyPolicy1 = """<insert here your privacy policy>"""

OpenSource1 = """Wusstest du schon, dass dieser Bot Open-Source ist? Er steht unter der AGPL 3.0 Lizenz. Der offizielle Quellcode für diesen Bot ist verfügbar unter:

https://github.com/djuelg/GoforPomodoro
(dies ist ein Fork von https://github.com/IThoughtUGNU/GoforPomodoro)

Weitere Informationen über die Lizenz können Sie hier nachlesen:

https://www.gnu.org/licenses/#AGPL
"""